// Included inside DreamVeilSkin namespace. This layout targets the audited snapshot only.
struct FNativeSkin {
 UWidgetBlueprint* BP; UWidgetTree* T; UCanvasPanel* Root;
 explicit FNativeSkin(UWidgetBlueprint* In):BP(In),T(In->WidgetTree) {
  Root=Cast<UCanvasPanel>(T->RootWidget);
  if(!Root&&BP->GetName()!=TEXT("WBP_PartEntry")){auto* Old=T->RootWidget.Get();Root=New<UCanvasPanel>(TEXT("RootCanvas"));T->RootWidget=Root;Place(Old,Root,0,0,1280,720);}
 }
 template<class W> W* New(const FString& Name){return T->ConstructWidget<W>(W::StaticClass(),FName(*(TEXT("DVI_")+Name)));}
 template<class W=UWidget> W* Get(const TCHAR* Name){auto* V=Cast<W>(T->FindWidget(FName(Name)));checkf(V,TEXT("Audited widget missing or wrong class: %s/%s"),*BP->GetName(),Name);return V;}
 void Place(UWidget* W,UCanvasPanel* C,float X,float Y,float Width,float Height,int32 Z=0){if(W->GetParent()!=C){W->RemoveFromParent();C->AddChild(W);}auto* S=CastChecked<UCanvasPanelSlot>(W->Slot);S->SetAnchors(FAnchors(0,0));S->SetAlignment(FVector2D(0,0));S->SetPosition(FVector2D(X,Y));S->SetSize(FVector2D(Width,Height));S->SetAutoSize(false);S->SetZOrder(Z);}
 void Pos(const TCHAR* Name,UCanvasPanel* C,float X,float Y,float W,float H){Place(Get(Name),C,X,Y,W,H);}
 UCanvasPanel* Inner(const TCHAR* Name){auto* P=Get<UPanelWidget>(Name);if(Cast<UButtonSlot>(P->Slot))FillSlot(P->Slot);auto Children=P->GetAllChildren();P->ClearChildren();auto* C=New<UCanvasPanel>(FString(TEXT("Layout_"))+Name);FillSlot(P->AddChild(C));for(auto* Child:Children)Place(Child,C,0,0,100,30);return C;}
 void Text(const TCHAR* Name,int32 Size,bool Center=false,bool Wrap=false){auto* W=Get<UTextBlock>(Name);StyleWidget(W,Size);W->SetAutoWrapText(Wrap);W->SetJustification(Center?ETextJustify::Center:ETextJustify::Left);}
 UTextBlock* Label(UCanvasPanel* C,const FString& Name,const FString& Value,float X,float Y,float W,float H,int32 Size=18,bool Center=false){auto* V=New<UTextBlock>(Name);V->SetText(FText::FromString(Value));StyleWidget(V,Size);V->SetJustification(Center?ETextJustify::Center:ETextJustify::Left);V->SetVisibility(ESlateVisibility::HitTestInvisible);Place(V,C,X,Y,W,H,2);return V;}
 UImage* Image(UCanvasPanel* C,const FString& Name,const FString& Asset,float X,float Y,float W,float H,int32 Z=-2,float Margin=0){auto* V=New<UImage>(Name);V->SetBrush(TextureBrush(Asset,Margin));V->SetVisibility(ESlateVisibility::HitTestInvisible);Place(V,C,X,Y,W,H,Z);return V;}
 void Back(UCanvasPanel* C,const FString& Name,float X,float Y,float W,float H,float Alpha=.94f,int32 Z=-10){auto* B=New<UBorder>(Name);B->SetBrush(FSlateColorBrush(FLinearColor(.008f,.008f,.012f,Alpha)));B->SetVisibility(ESlateVisibility::HitTestInvisible);Place(B,C,X,Y,W,H,Z);}
 void Panel(UCanvasPanel* C,const FString& Name,float X,float Y,float W,float H){Back(C,Name+TEXT("Fill"),X,Y,W,H);Image(C,Name+TEXT("Frame"),TEXT("Frames/T_Frame_Panel_9Slice"),X,Y,W,H,-3,.0625f);}
 void Mist(UCanvasPanel* C,const FString& Name,float X,float Y,float W,float H){auto* I=New<UImage>(Name);I->SetBrushFromMaterial(LoadObject<UMaterialInterface>(nullptr,TEXT("/Game/UI/DreamVeilSkin/Materials/M_UI_Mist")));I->SetVisibility(ESlateVisibility::HitTestInvisible);Place(I,C,X,Y,W,H,-1);}
 UDVVisual* Live(UCanvasPanel* C,const FString& Name,FName Mode,float X,float Y,float W,float H,int32 PartSlot=0,int32 Tier=0,bool Border=true,int32 Weapon=0){auto* V=New<UDVVisual>(Name);V->Mode=Mode;V->PreviewSlot=PartSlot;V->PreviewTier=Tier;V->bShowTier=Border;V->WeaponIndex=Weapon;V->SetVisibility(ESlateVisibility::HitTestInvisible);Place(V,C,X,Y,W,H,2);return V;}
 void Screen(){Back(Root,TEXT("ScreenDim"),0,0,1280,720,.68f,-20);}
 void Wrap(){auto* Size=New<USizeBox>(TEXT("ReferenceSize"));Size->SetWidthOverride(1280);Size->SetHeightOverride(720);Size->AddChild(Root);auto* Scale=New<UScaleBox>(TEXT("RootScale"));Scale->SetStretch(EStretch::ScaleToFit);Scale->SetStretchDirection(EStretchDirection::Both);Scale->AddChild(Size);T->RootWidget=Scale;Root->SetClipping(EWidgetClipping::ClipToBounds);}
 void Hud(){
  Back(Root,TEXT("StatusShade"),73,33,222,77,.58f);Back(Root,TEXT("TimerShade"),541,41,198,49,.58f);Back(Root,TEXT("ShardShade"),1094,48,144,38,.65f);Back(Root,TEXT("WeaponShade"),1040,616,198,57,.65f);
  Image(Root,TEXT("HudFrame"),TEXT("Frames/T_Frame_HUD"),0,0,1280,720,5);
  Pos(TEXT("Bar_Health"),Root,79,42,205,14);Pos(TEXT("Text_Health"),Root,88,37,190,24);Text(TEXT("Text_Health"),18);
  Pos(TEXT("Bar_Stamina"),Root,79,68,178,10);Pos(TEXT("Text_Level"),Root,83,88,49,20);Text(TEXT("Text_Level"),14);Pos(TEXT("Bar_Experience"),Root,135,93,107,6);
  Pos(TEXT("Text_DreamShards"),Root,1113,53,119,28);Text(TEXT("Text_DreamShards"),14);Image(Root,TEXT("ShardIcon"),TEXT("Icons/T_Icon_DreamShard"),1080,49,28,35,4);
  Pos(TEXT("Text_Weapon"),Root,1135,633,95,28);Text(TEXT("Text_Weapon"),18);Live(Root,TEXT("WeaponIcon"),TEXT("Weapon"),1041,620,86,44,0,0,false);
  Live(Root,TEXT("Timer"),TEXT("Timer"),551,45,178,40);Pos(TEXT("WBP_Corruption"),Root,0,0,1280,720);CastChecked<UCanvasPanelSlot>(Get(TEXT("WBP_Corruption"))->Slot)->SetZOrder(-15);
  Mist(Root,TEXT("StatusMist"),65,20,242,104);Mist(Root,TEXT("TimerMist"),512,21,257,90);
 }
 void Inventory(){
  Screen();Back(Root,TEXT("InventoryFill"),74,74,1132,584);Image(Root,TEXT("InventoryFrame"),TEXT("Frames/T_Frame_Inventory"),0,0,1280,720,1);
  auto* Border=Get<UBorder>(TEXT("Border_Background"));Border->SetBrushColor(FLinearColor::Transparent);Border->SetPadding(FMargin(0));Pos(TEXT("Border_Background"),Root,74,74,1132,528);
  auto* Main=Inner(TEXT("HB_Main"));Pos(TEXT("VB_Pistol"),Main,18,12,284,516);Pos(TEXT("Overlay_Rifle"),Main,823,12,292,516);Pos(TEXT("SB_PartList"),Main,329,74,472,442);
  Label(Main,TEXT("PartsTitle"),TEXT("보유 파츠"),332,29,455,34,22);Mist(Root,TEXT("InventoryMist"),70,69,1140,590);
  auto WeaponPanel=[&](const TCHAR* Box,const FString& Prefix,int32 Weapon){
   auto* C=Inner(Box);Text(*(TEXT("Text_")+Prefix+TEXT("Title")),24);Pos(*(TEXT("Text_")+Prefix+TEXT("Title")),C,19,16,240,34);
   Image(C,Prefix+TEXT("Icon"),TEXT("Icons/T_Icon_")+Prefix,19,66,246,123,0);
   const TCHAR* Stats[]={TEXT("Damage"),TEXT("FireRate"),TEXT("Range")};for(int32 I=0;I<3;I++){FString N=TEXT("Text_")+Prefix+Stats[I];Pos(*N,C,20,198+I*30,252,29);Text(*N,I==1?13:15);}
   FString Sockets=TEXT("VB_")+Prefix+TEXT("Sockets");Pos(*Sockets,C,14,300,260,205);auto* S=Inner(*Sockets);
   const TCHAR* Slots[]={TEXT("Muzzle"),TEXT("Magazine"),TEXT("Sight"),TEXT("Stock"),TEXT("Foregrip")};int32 Count=Weapon?5:3;
   for(int32 I=0;I<Count;I++){FString N=TEXT("Text_")+Prefix+Slots[I];Pos(*N,S,42,I*40,215,39);Text(*N,12,false,true);Live(S,Prefix+Slots[I]+TEXT("Slot"),TEXT("EquippedPart"),0,I*40,36,36,I,0,true,Weapon);}
  };
  WeaponPanel(TEXT("VB_Pistol"),TEXT("Pistol"),0);Pos(TEXT("Spacer_27"),CastChecked<UCanvasPanel>(Get(TEXT("Text_PistolTitle"))->GetParent()),0,0,0,0);WeaponPanel(TEXT("VB_Rifle"),TEXT("Rifle"),1);
  for(auto* W:Get<UOverlay>(TEXT("Overlay_Rifle"))->GetAllChildren()){if(auto* S=Cast<UOverlaySlot>(W->Slot)){S->SetHorizontalAlignment(HAlign_Fill);S->SetVerticalAlignment(W->GetName()==TEXT("Text_RifleLocked")?VAlign_Center:VAlign_Fill);S->SetPadding(FMargin(W->GetName()==TEXT("Text_RifleLocked")?18:0));}}
  Text(TEXT("Text_RifleLocked"),16,true,true);Pos(TEXT("HB_Shards"),Root,101,619,800,32);auto* Shard=Inner(TEXT("HB_Shards"));Pos(TEXT("Image_37"),Shard,0,0,26,32);Get<UImage>(TEXT("Image_37"))->SetBrushFromTexture(LoadObject<UTexture2D>(nullptr,TEXT("/Game/UI/DreamVeilSkin/Icons/T_Icon_DreamShard")));Pos(TEXT("Text_DreamShards"),Shard,38,3,760,28);Text(TEXT("Text_DreamShards"),18);
  Pos(TEXT("Button_Close"),Root,1040,612,148,42);
 }
 void PartEntry(){
  auto* Button=Get<UButton>(TEXT("Button_Row"));auto* C=Inner(TEXT("HorizontalBox_0"));Place(Get(TEXT("Text_Title")),C,58,6,255,44);Text(TEXT("Text_Title"),13,false,true);Place(Get(TEXT("Text_Effect")),C,321,6,140,44);Text(TEXT("Text_Effect"),12,false,true);Pos(TEXT("Spacer_77"),C,0,0,0,0);Live(C,TEXT("PartIcon"),TEXT("Part"),4,4,48,48);
  auto* Size=New<USizeBox>(TEXT("RowSize"));Size->SetMinDesiredWidth(472);Size->SetHeightOverride(56);Button->RemoveFromParent();Size->AddChild(Button);T->RootWidget=Size;
 }
 void Computer(){
  Screen();Panel(Root,TEXT("Computer"),74,74,1132,584);Label(Root,TEXT("ComputerTitle"),TEXT("꿈의 거래소"),105,95,235,34,24);Mist(Root,TEXT("ComputerMist"),70,72,1140,590);
  auto* B=Get<UBorder>(TEXT("Border_0"));B->SetBrushColor(FLinearColor::Transparent);B->SetPadding(FMargin(0));Pos(TEXT("Border_0"),Root,74,74,1132,584);auto* C=Inner(TEXT("VerticalBox_0"));
  Pos(TEXT("HB_Tabs"),C,291,17,549,43);auto* Tabs=Inner(TEXT("HB_Tabs"));const TCHAR* Btns[]={TEXT("Button_ShopTab"),TEXT("Button_SellTab"),TEXT("Button_EnhanceTab")};for(int32 I=0;I<3;I++)Pos(Btns[I],Tabs,I*186,0,177,43);
  Pos(TEXT("idgetSwitcher_Tabs"),C,20,76,1092,450);Pos(TEXT("Text_DreamShards"),C,68,548,860,30);Text(TEXT("Text_DreamShards"),18);Image(C,TEXT("ComputerShard"),TEXT("Icons/T_Icon_DreamShard"),31,545,29,35,2);Pos(TEXT("Button_Close"),C,966,539,150,43);
  auto* Shop=Inner(TEXT("VB_ShopPage"));Pos(TEXT("Text_ShopPage"),Shop,12,0,600,36);Text(TEXT("Text_ShopPage"),22);
  auto* Scroll=New<UScrollBox>(TEXT("ShopScroll"));Place(Scroll,Shop,8,44,1076,397);Scroll->SetConsumeMouseWheel(EConsumeMouseWheel::WhenScrollingPossible);auto* Rows=New<UVerticalBox>(TEXT("ShopRows"));Scroll->AddChild(Rows);
  auto ShopChildren=Shop->GetAllChildren();for(auto* Row:ShopChildren){if(!Row->GetName().StartsWith(TEXT("HB_")))continue;auto Original=CastChecked<UPanelWidget>(Row)->GetAllChildren();FString RowName=Row->GetName();auto* RC=Inner(*RowName);Row->RemoveFromParent();auto* Size=New<USizeBox>(RowName+TEXT("Size"));Size->SetHeightOverride(56);Size->AddChild(Row);auto* RS=Rows->AddChildToVerticalBox(Size);RS->SetPadding(FMargin(0,0,0,6));RS->SetHorizontalAlignment(HAlign_Fill);
   Back(RC,RowName+TEXT("Shade"),0,0,1060,56,.50f);int32 SlotIndex=0,Tier=0;const TCHAR* SlotNames[]={TEXT("Muzzle"),TEXT("Magazine"),TEXT("Sight"),TEXT("Stock"),TEXT("Foregrip")};for(int32 I=0;I<5;I++)if(RowName.Contains(SlotNames[I]))SlotIndex=I;for(int32 I=1;I<=4;I++)if(RowName.EndsWith(FString::Printf(TEXT("T%d"),I)))Tier=I-1;
   if(!RowName.Contains(TEXT("WeaponBuy")))Live(RC,RowName+TEXT("Icon"),TEXT("Fixed"),7,4,48,48,SlotIndex,Tier);
   else Image(RC,RowName+TEXT("RifleIcon"),TEXT("Icons/T_Icon_Rifle"),7,8,80,40,2);
   int32 TextIndex=0;for(auto* W:Original){if(Cast<UButton>(W)){Place(W,RC,880,7,165,42);continue;}if(auto* Tx=Cast<UTextBlock>(W)){float X=68,Width=170;if(TextIndex==1){X=256;Width=190;}if(TextIndex==2){X=453;Width=135;}if(TextIndex==3){X=605;Width=262;}Place(Tx,RC,X,16,Width,30);StyleWidget(Tx,15);TextIndex++;}}
   auto* BuyButton=Cast<UButton>(Original.Last());if(BuyButton&&BuyButton->GetChildrenCount()==0){auto* L=New<UTextBlock>(RowName+TEXT("BuyLabel"));L->SetText(FText::FromString(TEXT("구매")));StyleWidget(L,16);BuyButton->AddChild(L);}
  }
  auto Detail=[&](const TCHAR* Page,const TCHAR* Row,const TCHAR* List,const TCHAR* DetailBox,const FString& Kind){auto* P=Inner(Page);FString Header=TEXT("Text_")+Kind+TEXT("Page");Pos(*Header,P,12,0,600,36);Text(*Header,22);Pos(Row,P,11,46,1066,394);auto* R=Inner(Row);Pos(List,R,0,0,610,394);Pos(DetailBox,R,633,0,433,394);auto* D=Inner(DetailBox);Panel(D,Kind+TEXT("Panel"),0,0,433,394);Live(D,Kind+TEXT("SelectedIcon"),TEXT("SelectedPart"),174,20,86,86);
   FString Selected=TEXT("Text_Selected")+Kind+TEXT("Part");Pos(*Selected,D,18,123,397,52);Text(*Selected,18,true,true);FString Info=TEXT("Text_")+Kind+(Kind==TEXT("Sell")?TEXT("Price"):TEXT("Info"));Pos(*Info,D,28,189,377,72);Text(*Info,16,false,true);FString Result=TEXT("Text_")+Kind+(Kind==TEXT("Sell")?TEXT("Warning"):TEXT("Result"));Pos(*Result,D,28,267,377,57);Text(*Result,14,false,true);FString Button=TEXT("Button_")+Kind;Pos(*Button,D,117,336,200,42);};
  Detail(TEXT("VB_SellPage"),TEXT("HorizontalBox_77"),TEXT("SB_SellList"),TEXT("VB_SellDetail"),TEXT("Sell"));Detail(TEXT("VB_EnhancePage"),TEXT("HorizontalBox_336"),TEXT("SB_EnhanceList"),TEXT("VB_EnhanceDetail"),TEXT("Enhance"));
 }
 void Augment(){Screen();Pos(TEXT("VB_Main"),Root,0,0,1280,720);auto* C=Inner(TEXT("VB_Main"));Pos(TEXT("Text_Title"),C,240,119,800,47);Text(TEXT("Text_Title"),30,true);Pos(TEXT("HB_Choices"),C,164,205,952,372);auto* Choices=Inner(TEXT("HB_Choices"));for(int32 I=1;I<=3;I++){FString Button=FString::Printf(TEXT("Button_Choice%d"),I),Box=FString::Printf(TEXT("VB_Choice%d"),I);Pos(*Button,Choices,(I-1)*328,0,296,372);auto* D=Inner(*Box);auto Style=Get<UButton>(*Button)->GetStyle();Style.NormalPadding=FMargin(0);Style.PressedPadding=FMargin(0);Get<UButton>(*Button)->SetStyle(Style);FString N=FString::Printf(TEXT("Text_Choice%dName"),I),Desc=FString::Printf(TEXT("Text_Choice%dDesc"),I);Pos(*N,D,24,76,248,72);Text(*N,23,true,true);Pos(*Desc,D,24,174,248,140);Text(*Desc,17,false,true);Label(D,FString::Printf(TEXT("ChoiceNumber%d"),I),FString::Printf(TEXT("0%d"),I),24,23,248,32,18,true);Mist(D,FString::Printf(TEXT("ChoiceMist%d"),I),0,0,296,372);}}
 void Bed(){Screen();Panel(Root,TEXT("BedPanel"),366,217,548,286);Pos(TEXT("VB_Main"),Root,366,217,548,286);auto* C=Inner(TEXT("VB_Main"));Label(C,TEXT("BedHeading"),TEXT("다음 꿈으로"),34,36,480,40,28,true);Pos(TEXT("Text_Info"),C,38,98,472,63);Text(TEXT("Text_Info"),18,true,true);Pos(TEXT("Button_Go"),C,62,206,200,43);Pos(TEXT("Button_Cancel"),C,285,206,200,43);Mist(Root,TEXT("BedMist"),360,209,560,305);}
 void GameOver(){Screen();Panel(Root,TEXT("GameOverPanel"),350,204,580,312);auto* B=Get<UBorder>(TEXT("Border_0"));B->SetBrushColor(FLinearColor::Transparent);B->SetPadding(FMargin(0));Pos(TEXT("Border_0"),Root,350,204,580,312);auto* C=Inner(TEXT("VerticalBox_0"));Pos(TEXT("Text_Title"),C,30,46,520,48);Text(TEXT("Text_Title"),32,true);Pos(TEXT("Text_Info"),C,48,116,484,76);Text(TEXT("Text_Info"),17,true,true);Pos(TEXT("Button_Continue"),C,180,236,220,44);Mist(Root,TEXT("GameOverMist"),343,196,594,330);}
 void MainMenu(){
  Pos(TEXT("WidgetSwitcher_Menu"),Root,0,0,1280,720);
  auto* Main=Inner(TEXT("VerticalMain"));Pos(TEXT("Image"),Main,0,0,1280,720);CastChecked<UCanvasPanelSlot>(Get(TEXT("Image"))->Slot)->SetZOrder(-30);Back(Main,TEXT("MainDim"),0,0,1280,720,.45f,-20);Panel(Main,TEXT("MainPanel"),82,92,405,552);Pos(TEXT("Text_Title"),Main,111,130,348,64);Text(TEXT("Text_Title"),41,true);Label(Main,TEXT("MainSubtitle"),TEXT("꿈과 현실의 경계"),118,201,332,28,15,true);
  const TCHAR* Buttons[]={TEXT("Button_Continue"),TEXT("Button_Start"),TEXT("Button_Help"),TEXT("Button_Quit")};for(int32 I=0;I<4;I++)Pos(Buttons[I],Main,122,290+I*62,325,46);Pos(TEXT("Text_SaveInfo"),Main,112,557,345,59);Text(TEXT("Text_SaveInfo"),13,true,true);Mist(Main,TEXT("MainMist"),76,87,416,564);
  auto* Diff=Inner(TEXT("VerticalBox_Difficulty"));Pos(TEXT("Image_386"),Diff,0,0,1280,720);CastChecked<UCanvasPanelSlot>(Get(TEXT("Image_386"))->Slot)->SetZOrder(-30);Back(Diff,TEXT("DiffDim"),0,0,1280,720,.55f,-20);Panel(Diff,TEXT("DiffPanel"),205,115,870,490);Pos(TEXT("Text_DiffLabel"),Diff,250,151,780,48);Text(TEXT("Text_DiffLabel"),32,true);Pos(TEXT("Difficulty"),Diff,263,225,754,60);auto* Levels=Inner(TEXT("Difficulty"));const TCHAR* L[]={TEXT("Button_Easy"),TEXT("Button_Normal"),TEXT("Button_Hard")};for(int32 I=0;I<3;I++)Pos(L[I],Levels,I*258,0,238,60);Pos(TEXT("Text_DiffInfo"),Diff,268,337,744,122);Text(TEXT("Text_DiffInfo"),19,true,true);Pos(TEXT("HorizontalBox_128"),Diff,418,512,444,48);auto* Actions=Inner(TEXT("HorizontalBox_128"));Pos(TEXT("Button_StartRun"),Actions,0,0,210,48);Pos(TEXT("Button_Back"),Actions,234,0,210,48);Mist(Diff,TEXT("DiffMist"),200,110,880,500);
  auto* Help=Inner(TEXT("VerticalBox_Help"));Back(Help,TEXT("HelpDim"),0,0,1280,720,.82f,-20);Panel(Help,TEXT("HelpPanel"),148,99,984,534);Label(Help,TEXT("HelpHeading"),TEXT("안내"),186,128,900,45,30);Pos(TEXT("HorizontalBox_HelpTabs"),Help,186,200,174,285);auto* HT=Inner(TEXT("HorizontalBox_HelpTabs"));const TCHAR* HB[]={TEXT("Button_HelpGame"),TEXT("Button_HelpDiff"),TEXT("Button_HelpSave"),TEXT("Button_HelpKeys")};for(int32 I=0;I<4;I++)Pos(HB[I],HT,0,I*61,174,47);Pos(TEXT("SizeBox_HelpBody"),Help,385,188,702,346);Get<USizeBox>(TEXT("SizeBox_HelpBody"))->ClearWidthOverride();Get<USizeBox>(TEXT("SizeBox_HelpBody"))->ClearHeightOverride();Pos(TEXT("Button_BackFromHelp"),Help,908,562,185,44);for(auto* Page:Get<UWidgetSwitcher>(TEXT("WidgetSwitcher_Help"))->GetAllChildren()){if(auto* S=Cast<UScrollBox>(Page)){for(auto* Child:S->GetAllChildren()){if(auto* Tx=Cast<UTextBlock>(Child)){StyleWidget(Tx,16);Tx->SetAutoWrapText(true);CastChecked<UScrollBoxSlot>(Tx->Slot)->SetPadding(FMargin(18,9));}}}}
 }
 void Run(){T->ForEachWidget([](UWidget* W){StyleWidget(W,16);});const FString N=BP->GetName();if(N==TEXT("WBP_HUD"))Hud();else if(N==TEXT("WBP_Inventory"))Inventory();else if(N==TEXT("WBP_PartEntry")){PartEntry();return;}else if(N==TEXT("WBP_Computer"))Computer();else if(N==TEXT("WBP_AugmentChoice"))Augment();else if(N==TEXT("WBP_Bed"))Bed();else if(N==TEXT("WBP_GameOver"))GameOver();else if(N==TEXT("WBP_MainMenu"))MainMenu();Wrap();}
};
